"""empty message

Revision ID: d5a7754c69d0
Revises: b4dbe50fb6c5
Create Date: 2024-02-05 13:50:30.236913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a7754c69d0'
down_revision = 'b4dbe50fb6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('current_funding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_funding', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
